- name: Create a share directory if it does not exist
  file:
    path: "{{ share_dir }}"
    state: directory
    owner: root
    group: root

- name: install cifs-utils
  yum:
    name: cifs-utils

- name: Template configuration file for backup share
  template:
    src: '.backup_credentials.j2'
    dest: '/root/.backup_credentials'
    mode: 600

- name: "mount backup share"
  mount:
    state: "mounted"
    fstype: "cifs"
    name: "{{ share_dir }}"
    src: "{{ share_path }}"
    opts: "credentials=/root/.backup_credentials,file_mode=0640,dir_mode=0750,gid=root,uid=root"

- name: backup www
  include_tasks: www.yml
  
- name: backup DB
  include_tasks: db.yml
  
